
function setLevel(p: player, l: number) :: number:
	set {_u} to uuid of {_p}
	set {level::%{_u}%} to {_l}
	return {_l}

function getLevel(p: player) :: number:
	set {_u} to uuid of {_p}
	return {level::%{_u}%} ? 0

function nextLevel(p: player):
	set {_n} to getLevel({_p}) + 1
	setLevel({_p}, {_n})
	teleportToLevel({_p})

function teleportToLevel(p: player):
	teleport {_p} to getMapLevel(getGameMap(), getLevel({_p}))
